on: Build executor docker base image

on:
  repository_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out master
        uses: actions/checkout@v2
        with:
          presist-credentials: false
          fetch-depth: 0

      - name: Setup QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        if: github.event.action == 'prerelease'
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          build-args:
            - COVALENT_BASE_IMAGE: '${{ github.event.client_payload.covalent_base_image }}'
          platforms: all
          push: true
          tags: |
            public.ecr.aws/covalent-executor-base/covalent:latest
            public.ecr.aws/covalent-executor-base/covalent:${{ github.event.client_payload.tag }}

      # Instead of updating the image tag, we build the image again b/c the FROM for the stable image build is
      # possibly different from the image already present in the ECR
      - name: Build stable release
        uses: docker/build-push-action@v2
        if: github.event.action == 'stable'
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          build-args:
            - COVALENT_BASE_IMAGE: '${{ github.event.client_payload.covalent_base_image }}'
          platforms: all
          push: true
          tags: |
            public.ecr.aws/covalent-executor-base/covalent:latest
            public.ecr.aws/covalent-executor-base/covalent:stable

          
