# Copyright 2021 Agnostiq Inc.
#
# This file is part of Covalent.
#
# Licensed under the GNU Affero General Public License 3.0 (the "License").
# A copy of the License may be obtained with this software package or at
#
#      https://www.gnu.org/licenses/agpl-3.0.en.html
#
# Use of this file is prohibited except in compliance with the License. Any
# modifications or derivative works of this file must retain this copyright
# notice, and modified files must contain a notice indicating that they have
# been altered from the originals.
#
# Covalent is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the License for more details.
#
# Relief from the License may be granted by purchasing a commercial license.

name: docker

on:
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        description: "AWS Plugins version number, e.g. 0.32.3"
        type: string
      prerelease:
        description: "true: Create a prerelease. false: Create a stable release"
        required: true
        type: boolean
        default: true
  workflow_call:
    inputs:
      prerelease:
        description: "true: Create a prerelease. false: Create a stable release"
        required: true
        type: boolean
        default: true

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      prerelease: true
      version: ${{ inputs.stable_verion }}
      covalent_version: "covalent>=0.202.0,<1"
    steps:
      - name: Check out release tag
        uses: actions/checkout@v2
        if: >
          env.version
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: "v${{ env.version }}"

      - name: Checkout default branch (develop)
        uses: actions/checkout@v2
        if: >
          !env.version
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "linux/amd64"

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ECR_PUBLIC_UPLOAD_ROLE }}
          aws-region: us-east-1

      - name: Login to Public registry
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

      - name: Generate Tag
        run: |
          TAG="$(cat ./VERSION)"

          pip install ${{ env.covalent_version }}
          package_info=$(pip show covalent)

          package_version=$(echo "$package_info" | grep -E '^Version: ' | cut -d' ' -f2)

          major_version=$(echo "$package_version" | sed -E 's/^([0-9]+)\..*$/\1/')
          minor_version=$(echo "$package_version" | sed -E 's/^[0-9]+\.([0-9]+)\..*$/\1/')
          patch_version=$(echo "$package_version" | sed -E 's/^[0-9]+.[0-9]+\.([0-9]+).*$/\1/')

          echo "Major version: $major_version"
          echo "Minor version: $minor_version"
          echo "Patch version: $patch_version"

          COV_VER_TAG="$major_version-$minor_version-$patch_version"

          echo "COV_VER_TAG: $COV_VER_TAG"
          echo "TAG: $TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "COV_VER_TAG=$COV_VER_TAG" >> $GITHUB_ENV

      - name: Build and push pre-release image version
        if: >
          env.prerelease
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          files: Dockerfile
          platforms: "linux/amd64"
          push: true
          build-args: |
            COVALENT_BASE_IMAGE=python:3.8-slim-bullseye
            COVALENT_PACKAGE_VERSION=${{ env.covalent_version }}
            PRE_RELEASE=false
          tags: |
            public.ecr.aws/covalent/covalent-executor-base:latest
            public.ecr.aws/covalent/covalent-executor-base:${{ env.TAG }}
            public.ecr.aws/covalent/covalent-executor-base:${{ env.COV_VER_TAG }}

      # - name: Build and push stable version
      #   if: >
      #     !env.prerelease
      #     && github.event_name == 'workflow_dispatch'
      #     && env.version
      #   uses: docker/build-push-action@v2
      #   with:
      #     builder: ${{ steps.buildx.outputs.name }}
      #     context: .
      #     files: Dockerfile
      #     platforms: "linux/amd64"
      #     push: true
      #     build-args: |
      #       COVALENT_BASE_IMAGE=python:3.8-slim-buster
      #       COVALENT_PACKAGE_VERSION=covalent>=0.202.0,<1
      #     tags: |
      #       public.ecr.aws/covalent/covalent-executor-base:stable
